---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  SECRET_ARN:
    {{- .Values.configmap.secret_arn | nindent 4 }}
  AWS_REGION:
    {{- .Values.configmap.aws_region | nindent 4 }}